### ISSUE TITLE
Backwards incompatible change: Indentation

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/eslint-config-onelint#14]
@PabloSichert added a rule enforcing indentation of `case` statements in `switch` blocks.

The following is considered valid:

``` js
switch (foo) {
    case 'bar':
        console.log('bar');
        break;
    default:
        console.log('foo');
}
```

The following is considered invalid:

``` js
switch (foo) {
case 'bar':
    console.log('bar');
    break;
default:
    console.log('foo');
}
```

I spotted the latter style a few places in the webmail. How do you feel about this? Do you have any compelling arguments for either case? Personally I think that the first makes most sense.

This will be a breaking change compared to the old onelint setup, as that did not enforce either style.

/cc @papandreou @birkestroem @lusia @mwoc @joelmukuthu @dpiccone @PabloSichert

**Comment by papandreou** [comment]
I prefer keeping the `case` labels at the same level as the `switch`, mostly to avoid overindentation, but I know the world is divided about it. I've seen the discussion pop up in the context of every language that supports a `switch`/`case` construct.

I'm not religious about it -- I think jslint enforced that style and I just chose to follow along. I can easily change my style if there's a consensus.

Then again, this feels like a discussion that's really not worth our time.

**Comment by gustavnikolaj** [comment]
Completely agree that arguments over style are a complete waste of time. Unless there's any arguments against it, I'll go with whatever is over represented in our combined code base.

We have a mix of both styles in the webmail, and jshint doesn't complain about either. I think it might have regressed when we upgraded jshint and introduced jscs. 

Either way, I think we should choose one style, and stick with it, even though it is going to be a breaking change. Consistency is king. And it is fixable by eslint, so it won't be a problem :-)

**Comment by pablosichert** [comment]
Agree with you guys.

The arguments for either way to indent the statement makes sense and I would be fine with any of them, as long as one of them is enforced.

Actually I made the decision on the first appearance of a switch statement I found in the webmail suite, but didn't examine what the general consensus in the project was.

**Comment by gustavnikolaj** [comment]
I did a quick test running the linter against the webmail with either settings. Found a smaller amount of error when favoring non-indentation of case statements, so that is the one we go with :-)

**Comment by gustavnikolaj** [comment]
I enforce no indentation of case statements now, as per the commit referenced above. It will go out with the v1.0.0 release.
