### ISSUE TITLE
Backwards incompatible change: Unused variables

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/eslint-config-onelint#15]
jshint's version of this rule did not check function parameters. eslint does.

**Comment by papandreou** [comment]
Won't that be a problem with express, which treats middleware differently depending on whether it takes 4 parameters (err, req, res, next) or 3 or less (req, res, next)?

I have an error handler that doesn't call `next`, will eslint complain?

**Comment by gustavnikolaj** [comment]
You're right... It will be a problem in those cases.

There's 3 options for the no-unused-vars rule arguments validation pattern in eslint@1:
- all (must use all args)
- none (no validation)
- after-used (the last argument must be used - arguments before the first one are allowed to be unused) <- this is the default

We can configure it to not validate the function args.

http://eslint.org/docs/1.0.0/rules/no-unused-vars

In eslint@2 you can further configure the rule, to allow defining and ignore pattern for unused args in functions: http://eslint.org/docs/rules/no-unused-vars#argsignorepattern - if the ignore pattern is set to `/^_/`:

This would be a problem if next was not used:

``` js
function (err, req, res, next) {...}
```

This would not:

``` js
function (err, req, res, _next) {...}
```

---

I quite like the argument validation, but I do see the potential for problems. Is the ignore-pattern-thing an acceptable compromise?

**Comment by joelmukuthu** [comment]
I think they can also be useful as some sort of documentation, especially
for callback functions. It saves time when you're reading through code and
trying to figure out how some other function calls the callback. Other than
that, and I could be wrong here, I don't see any harm in having them.

**Comment by papandreou** [comment]
I don't see the harm either. My vote is "none".

**Comment by gustavnikolaj** [comment]
After having thought about it, I agree. It's the right thing to do - at the very least for now, where the primary goal is to get as close as possible to zero changes when swapping this in for the existing linting tool chain.
