### ISSUE TITLE
Backwards incompatible change: Single Quotes

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/eslint-config-onelint#3]
As far as I can tell, nothing in the old jscs or jshint configuration said anything about quoting.

This iteration will require us to use single quotes unless avoiding escaping single quotes by using double quotes instead.

This is what we have been doing until now anyway, so I hope it will not be too bad of a change.

Document this in the readme, describing how to disable it temporarily if necessary.

**Comment by papandreou** [comment]
:+1:

**Comment by gustavnikolaj** [comment]
Fixed with #26
