### ISSUE TITLE
RFC: Onelint version 2.0.0

### ISSUE THREAD

**Issue by gustavnikolaj** [One-com/eslint-config-onelint#30]
There's a milestone tracking the features planned for the next major version: https://github.com/One-com/eslint-config-onelint/milestone/4

Currently the following breaking changes are planned:

### 1. Prefer single quotes

Always use single quotes. Implementation: #26 

```js
var foo = 'using single quotes';
var bar = "except when they can be used to avoid escaping ' (single quotes)";
var baz = `also, allow template literals`.
```

From what I can tell, this is exactly how it is already used in the code bases using the onelint style. We just haven't been able to enforce it until we changed to eslint. I originally wanted to add this in v1 - but found that we didn't actually enforce it in the existing onelint-configuration - which is why it ended up being postponed to a later version.

It should be `--fix`-able for the most part.

This change requires that we bump the required eslint version to 3.

### 2. Handle errors in callbacks

Always handle err argument in Node.js style callbacks. Implementation: #29 

```js
someAsyncAction(function (err, data) {
    if (err) {} // This is okay
});

someAsyncAction(function (err, data) {
    // This is bad
});
```

This is as the first suggestion something that we already do in all the code that I'm aware of. I'm not concerned about the breaking changes caused by this one, as it is very likely to uncover new bugs.

### 3. Upgrade required eslint version to 3.

This is a requirement for improved auto-fixing and some newer rules, like the `avoidEscape` option used in the first point.

It also means that we drop support for node versions lower than 4, as eslint did. As node 0.10 is out of maintenance mode, and node 0.12 will follow at new years, this might be a good time.

---

Do anyone have suggestions for other features to include in this or future major versions, please feel free to list them here. I'm pinging relevant stakeholders for feedback and new ideas, internal as well as external users.

Considering the vast amount of code using this linter setup, the bar for breaking changes should be very high. Rules that enforce things we already do (this should by definition be agreed upon by all of us) or rules that solve obvious problems (like the missing error handling of callbacks) are generally good candidates. Stylistic changes are out of scope.

I'll volunteer my time to upgrade external projects that is burdened with extra yak-shave work following these changes.

@lusia @dominicrj23 @papandreou @moubi @dpiccone @PabloSichert @joelmukuthu @birkestroem  @sunesimonsen (unexpected) @Munter (assetgraph)

**Comment by papandreou** [comment]
:+1:

**Comment by moubi** [comment]
I would suggest this one:
- Always use `const` for one time assignments:  
  _We can use `let` for all other cases._

http://eslint.org/docs/rules/prefer-const.html 
http://eslint.org/docs/rules/no-const-assign.html

I find it useful is it allows to see with a single look if a variable is going to be redefined down in code.

**Comment by gustavnikolaj** [comment]
@moubi I agree, but I'm afraid that we won't be able to add it, as we still have a lot of code that targets ES5 environments. It is not a problem for server-side code, as most projects should be able to ditch support for node versions older than 4.0.0, but we're not quite there for our frontend code yet, and unexpected also still targets es5 browsers.

**Comment by danielepiccone** [comment]
I'd propose to add `no-multiple-empty-line` like @PabloSichert added in Taskmate which proved useful.

https://github.com/One-com-webdev/taskmate/blob/68dde454a6be70c0304427e4f4077a7a930d7aa4/.eslintrc.js#L12

Don't know the impact on older projects, but I'd keep the default settings of allowing at most 2 consecutive lines to keep it more relaxed.

**Comment by gustavnikolaj** [comment]
@dpiccone in my opinion that is a stylistic change. If we were to make it consistent with the established style in the projects, we seem to use at most 1 empty line at a time. Personally, I'm not sure I think it passes the bar - but let's hear what the others think.

**Comment by pablosichert** [comment]
Agree with you, @gustavnikolaj. I put it in Taskmate because we, those working on the project, could agree on having it strictly to a single line.

Because of its stylistic nature I don't think it has any priority for a general rule.

If we happen to all agree with it we could still include it, of course.

**Comment by joelmukuthu** [comment]
The [update to eslint 3](https://github.com/One-com/eslint-config-onelint/pull/31) would be included in this, right? The breaking change there is adding a peer dependency on eslint v3

**Comment by pablosichert** [comment]
Poll for `'no-multiple-empty-lines': ['error', { max: 1, maxBOF: 0, maxEOF: 0 }]`. (That means <= 1 `\n` at the end of file, combined with `'eol-last'` = 1 `\n`)

A single down vote means not including it.

**Comment by gustavnikolaj** [comment]
@joelmukuthu I added a third section to the original issue about bumping eslint to 3.0.0. If it's a blocking anyone I guess they can keep using the `1.x` branch until they are able to ditch node pre-4. But for completeness sake.

**Comment by joelmukuthu** [comment]
@gustavnikolaj great. thanks for doing the research :)

**Comment by joelmukuthu** [comment]
For those of us who use atom with the eslint plugin, `no-multiple-empty-lines` also requires eslint 3 as a peer dependency or we'll have that nasty bug in the editor. `eslint >= 3.8` IIRC

**Comment by gustavnikolaj** [comment]
v2.0.0 is now out. https://github.com/One-com/eslint-config-onelint/commit/9838faba65610071d7515aba304853db4d74a865

I have created a legacy v1 branch for the projects that still aren't able to ditch node versions before 4.0.0.
